// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsEsVwqmKGU9dqe8BBeRA1Yel7WWdTDBI',
    appId: '1:25580554871:web:2537e1ca502485eeead472',
    messagingSenderId: '25580554871',
    projectId: 'mushtary-sa',
    authDomain: 'mushtary-sa.firebaseapp.com',
    storageBucket: 'mushtary-sa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmVlqbx9Izp9BKpzg9npHvYW0PhUkZDhU',
    appId: '1:25580554871:android:b8df3a84b16fda02ead472',
    messagingSenderId: '25580554871',
    projectId: 'mushtary-sa',
    storageBucket: 'mushtary-sa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPGdgzaGXLoazcm02UDizDvjZsS71PwV8',
    appId: '1:25580554871:ios:9c71345968b74301ead472',
    messagingSenderId: '25580554871',
    projectId: 'mushtary-sa',
    storageBucket: 'mushtary-sa.firebasestorage.app',
    iosBundleId: 'com.rasad.sa.mushtary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsEsVwqmKGU9dqe8BBeRA1Yel7WWdTDBI',
    appId: '1:25580554871:web:b7062114b56cdf0eead472',
    messagingSenderId: '25580554871',
    projectId: 'mushtary-sa',
    authDomain: 'mushtary-sa.firebaseapp.com',
    storageBucket: 'mushtary-sa.firebasestorage.app',
  );
}
